stages:
  - build
  - deploy

build project:
  stage: build
  image: node:18.12.1
  script:
    - npm  install
    - npm run build
  artifacts:
    paths:
      - build/

deploy project:
  stage: deploy
  image: node:18.12.1
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
